name: Demo 05 - Pull Request

on:
  pull_request:
    branches: 
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-test-branch:
    name: "Build and Test Of PR"
    runs-on: ubuntu-latest

    steps:
      # Ensure this is commented out to allow the PR to pass!
      # - name: Make PR Fail
      #   run: exit 1

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x 

      - name: Install dependencies
        run: dotnet restore "${{ github.workspace }}/mywebapp/mywebapp.sln"
      
      - name: Build
        run: dotnet build "${{ github.workspace }}/mywebapp/mywebapp.sln" --configuration Release --no-restore
      
      - name: Test
        run: |
          dotnet test "${{ github.workspace }}/mywebapp/mywebapp.sln" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: XUnit Tests
          path: "**/test-results.trx"
          reporter: dotnet-trx
        
      - name: Publish
        # We run this from the 'src' directory to ensure Program.cs is found
        working-directory: ./mywebapp/src
        run: dotnet publish mywebapp.csproj -c Release -o ../../publish
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mywebappbuildartifacts
          path: ./publish/**
          if-no-files-found: error
